services:
  - type: web
    name: api
    env: docker
    dockerfilePath: Dockerfile
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
  - type: worker
    name: pdf-worker
    env: docker
    dockerfilePath: Dockerfile
    startCommand: dotnet worker/Worker.dll
  - type: postgres
    name: db
  - type: redis
    name: cache
  - type: cron
    name: usage-aggregator
    schedule: "0 0 * * *"
    command: dotnet worker/Worker.dll --cron
