name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore SwissTax.sln
      - run: dotnet build SwissTax.sln --no-restore
      - run: dotnet test tests/ApiTests/ApiTests.csproj --no-build
      - run: docker build -t swisstax .
